import { db } from '@/lib/db'
import { toast } from 'sonner'

export interface DetailingApproval {
  detailingId: string
  approvedBy: string
  approvalDate: string
  revisionNumber: number
  drawingIds: string[]
}

export interface AutoGeneratedFabPackage {
  id: string
  name: string
  projectId: string
  workPackageId?: string
  detailingIds: string[]
  drawingIds: string[]
  pieceMarks: string[]
  status: 'pending_materials' | 'ready_for_fab' | 'in_fabrication'
  createdFrom: 'detailing_approval'
  createdAt: string
}

export class DetailingFabIntegration {
  async processDetailingApproval(approval: DetailingApproval): Promise<AutoGeneratedFabPackage | null> {
    try {
      const detailing = await db.detailings.get(approval.detailingId)
      if (!detailing) return null
      
      await db.detailings.update(approval.detailingId, {
        status: 'approved',
        approvedBy: approval.approvedBy,
        approvedAt: approval.approvalDate,
        currentRevision: approval.revisionNumber
      })
      
      const shouldAutoCreatePackage = await this.checkAutoCreateCriteria(detailing)
      
      if (shouldAutoCreatePackage) {
        const fabPackage = await this.createFabPackage(detailing, approval)
        await this.notifyFabTeam(fabPackage)
        return fabPackage
      }
      
      return null
    } catch (error) {
      console.error('Error processing detailing approval:', error)
      toast.error('Failed to process detailing approval')
      return null
    }
  }
  
  private async checkAutoCreateCriteria(detailing: any): Promise<boolean> {
    if (detailing.autoCreateFabPackage === false) return false
    
    if (!detailing.workPackageId) return true
    
    const workPackage = await db.workPackages.get(detailing.workPackageId)
    if (!workPackage) return true
    
    const relatedDetailings = await db.detailings
      .where('workPackageId')
      .equals(detailing.workPackageId)
      .toArray()
    
    const allApproved = relatedDetailings.every(d => 
      d.id === detailing.id || d.status === 'approved'
    )
    
    return allApproved
  }
  
  private async createFabPackage(detailing: any, approval: DetailingApproval): Promise<AutoGeneratedFabPackage> {
    const drawings = await db.drawings
      .where('id')
      .anyOf(approval.drawingIds)
      .toArray()
    
    const pieceMarks = drawings
      .flatMap(d => d.pieceMarks || [])
      .filter((mark, index, self) => self.indexOf(mark) === index)
    
    const packageName = detailing.workPackageId 
      ? (await db.workPackages.get(detailing.workPackageId))?.name || `Package ${Date.now()}`
      : `Auto Package - ${detailing.name}`
    
    const fabPackage: AutoGeneratedFabPackage = {
      id: `fab-pkg-${Date.now()}`,
      name: packageName,
      projectId: detailing.projectId,
      workPackageId: detailing.workPackageId,
      detailingIds: [detailing.id],
      drawingIds: approval.drawingIds,
      pieceMarks,
      status: 'pending_materials',
      createdFrom: 'detailing_approval',
      createdAt: new Date().toISOString()
    }
    
    await db.fabricationPackages.add(fabPackage)
    
    if (detailing.workPackageId) {
      await db.workPackages.update(detailing.workPackageId, {
        status: 'Detailing Complete - Pending Materials',
        fabricationPackageId: fabPackage.id,
        updatedAt: new Date().toISOString()
      })
    }
    
    await this.createDetailingRevision(detailing.id, approval)
    
    toast.success('Fabrication Package Created', {
      description: `${packageName} created from approved detailing`,
      action: {
        label: 'View',
        onClick: () => window.location.href = `/projects/${detailing.projectId}/fab-tracking`
      }
    })
    
    return fabPackage
  }
  
  private async createDetailingRevision(detailingId: string, approval: DetailingApproval): Promise<void> {
    await db.detailingRevisions.add({
      id: `rev-${Date.now()}`,
      detailingId,
      revisionNumber: approval.revisionNumber,
      status: 'approved',
      approvedBy: approval.approvedBy,
      approvedAt: approval.approvalDate,
      description: `Approved revision ${approval.revisionNumber}`,
      drawingIds: approval.drawingIds,
      createdAt: approval.approvalDate
    })
  }
  
  private async notifyFabTeam(fabPackage: AutoGeneratedFabPackage): Promise<void> {
    await db.notifications.add({
      id: `notif-fab-${Date.now()}`,
      projectId: fabPackage.projectId,
      userId: 'fab-team',
      type: 'new_fab_package',
      title: 'New Fabrication Package Ready',
      message: `${fabPackage.name} is pending materials verification`,
      link: `/projects/${fabPackage.projectId}/fab-tracking`,
      read: false,
      createdAt: new Date().toISOString()
    })
  }
  
  async updateFabPackageFromDetailing(detailingId: string): Promise<void> {
    const fabPackages = await db.fabricationPackages
      .where('detailingIds')
      .equals(detailingId)
      .toArray()
    
    const detailing = await db.detailings.get(detailingId)
    if (!detailing) return
    
    for (const pkg of fabPackages) {
      const allDetailingsApproved = await this.checkAllDetailingsApproved(pkg.detailingIds)
      
      if (allDetailingsApproved && pkg.status === 'pending_materials') {
        const allMaterialsReceived = await this.checkMaterialsStatus(pkg.pieceMarks)
        
        if (allMaterialsReceived) {
          await db.fabricationPackages.update(pkg.id, {
            status: 'ready_for_fab',
            updatedAt: new Date().toISOString()
          })
          
          toast.success('Package Ready', {
            description: `${pkg.name} is ready for fabrication`
          })
        }
      }
    }
  }
  
  private async checkAllDetailingsApproved(detailingIds: string[]): Promise<boolean> {
    const detailings = await db.detailings
      .where('id')
      .anyOf(detailingIds)
      .toArray()
    
    return detailings.every(d => d.status === 'approved')
  }
  
  private async checkMaterialsStatus(pieceMarks: string[]): Promise<boolean> {
    const marks = await db.pieceMarks
      .where('mark')
      .anyOf(pieceMarks)
      .toArray()
    
    return marks.every(m => 
      m.materialStatus === 'Received' || m.materialStatus === 'In Stock'
    )
  }
  
  async getDetailingApprovalWorkflow(detailingId: string): Promise<any> {
    const detailing = await db.detailings.get(detailingId)
    if (!detailing) return null
    
    const revisions = await db.detailingRevisions
      .where('detailingId')
      .equals(detailingId)
      .toArray()
    
    const drawings = await db.drawings
      .where('id')
      .anyOf(detailing.drawingIds || [])
      .toArray()
    
    const fabPackages = await db.fabricationPackages
      .where('detailingIds')
      .equals(detailingId)
      .toArray()
    
    return {
      detailing,
      revisions: revisions.sort((a, b) => b.revisionNumber - a.revisionNumber),
      drawings,
      fabricationPackages: fabPackages,
      currentStatus: this.getWorkflowStatus(detailing, revisions, fabPackages)
    }
  }
  
  private getWorkflowStatus(detailing: any, revisions: any[], fabPackages: any[]): string {
    if (fabPackages.some(p => p.status === 'in_fabrication')) {
      return 'In Fabrication'
    }
    
    if (fabPackages.some(p => p.status === 'ready_for_fab')) {
      return 'Ready for Fabrication'
    }
    
    if (detailing.status === 'approved') {
      return 'Approved - Pending Package Creation'
    }
    
    if (revisions.length > 0) {
      return 'Under Review'
    }
    
    return 'In Progress'
  }
}

export const detailingFabIntegration = new DetailingFabIntegration()
