import { v4 as uuidv4 } from 'uuid'

export interface ExtendedWorkPackage {
  id: string
  projectId: string
  name: string
  packageNumber: string
  title: string
  type: 'fabrication' | 'erection'
  description?: string
  status: 'planning' | 'ready' | 'in-progress' | 'fabricated' | 'shipped' | 'erected' | 'completed'
  startDate?: string
  completionDate?: string
  assignedCrew?: string
  drawings: string[]
  materials: string[]
  scheduledValue: number
  percentComplete: number
  approvedForBilling: boolean
  billedDate?: string
  billedInSOVVersion?: string
  costCodeId?: string
  taskId?: string
  createdAt: string
  updatedAt?: string
}

export interface FieldProgressUpdate {
  workPackageId: string
  status: ExtendedWorkPackage['status']
  percentComplete: number
  updatedBy: string
  updatedAt: string
  notes?: string
}

export interface SOVLineItem {
  id: string
  versionId: string
  lineNumber: number
  description: string
  scheduledValue: number
  workCompleted: number
  materialsStored: number
  totalCompleted: number
  retainage: number
  currentBilling: number
  previouslyBilled: number
  balance: number
  workPackageId?: string
  costCodeId?: string
  autoGenerated: boolean
  createdAt: string
}

export interface BillingApprovalResult {
  success: boolean
  workPackage: ExtendedWorkPackage
  sovLineItem?: SOVLineItem
  message: string
}

export async function approveWorkPackageForBilling(
  projectId: string,
  workPackageId: string,
  approvedBy: string
): Promise<BillingApprovalResult> {
  try {
    const workPackagesKey = `work-packages-${projectId}`
    const workPackagesData = await spark.kv.get<ExtendedWorkPackage[]>(workPackagesKey) || []
    
    const workPackage = workPackagesData.find(wp => wp.id === workPackageId)
    
    if (!workPackage) {
      return {
        success: false,
        workPackage: null as any,
        message: 'Work package not found'
      }
    }

    if (workPackage.status !== 'erected' && workPackage.status !== 'completed') {
      return {
        success: false,
        workPackage,
        message: 'Work package must be erected or completed to approve for billing'
      }
    }

    if (workPackage.approvedForBilling) {
      return {
        success: false,
        workPackage,
        message: 'Work package already approved for billing'
      }
    }

    const updatedWorkPackage: ExtendedWorkPackage = {
      ...workPackage,
      approvedForBilling: true,
      updatedAt: new Date().toISOString()
    }

    const updatedWorkPackages = workPackagesData.map(wp => 
      wp.id === workPackageId ? updatedWorkPackage : wp
    )
    await spark.kv.set(workPackagesKey, updatedWorkPackages)

    const sovLineItem = await createSOVLineItemFromWorkPackage(projectId, updatedWorkPackage)

    return {
      success: true,
      workPackage: updatedWorkPackage,
      sovLineItem,
      message: 'Work package approved for billing and added to SOV'
    }
  } catch (error) {
    console.error('Error approving work package for billing:', error)
    return {
      success: false,
      workPackage: null as any,
      message: `Failed to approve work package: ${error}`
    }
  }
}

async function createSOVLineItemFromWorkPackage(
  projectId: string,
  workPackage: ExtendedWorkPackage
): Promise<SOVLineItem | undefined> {
  try {
    const sovVersionsKey = `sov-versions-${projectId}`
    const sovItemsKey = `sov-items-${projectId}`
    
    const sovVersions = await spark.kv.get<any[]>(sovVersionsKey) || []
    const sovItems = await spark.kv.get<SOVLineItem[]>(sovItemsKey) || []
    
    let activeVersion = sovVersions.find(v => v.status === 'draft')
    
    if (!activeVersion) {
      activeVersion = {
        id: uuidv4(),
        projectId,
        versionNumber: sovVersions.length + 1,
        periodStart: new Date().toISOString().split('T')[0],
        periodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        status: 'draft',
        retainagePercent: 10,
        createdAt: new Date().toISOString(),
        notes: 'Auto-generated from field progress'
      }
      sovVersions.push(activeVersion)
      await spark.kv.set(sovVersionsKey, sovVersions)
    }

    const existingLineItem = sovItems.find(item => 
      item.versionId === activeVersion.id && item.workPackageId === workPackage.id
    )

    if (existingLineItem) {
      return existingLineItem
    }

    const lineNumber = sovItems.filter(item => item.versionId === activeVersion.id).length + 1
    
    const workCompleted = (workPackage.scheduledValue || 0) * (workPackage.percentComplete / 100)
    const totalCompleted = workCompleted
    const retainage = totalCompleted * (activeVersion.retainagePercent / 100)
    const currentBilling = totalCompleted - retainage

    const newLineItem: SOVLineItem = {
      id: uuidv4(),
      versionId: activeVersion.id,
      lineNumber,
      description: workPackage.name || workPackage.title,
      scheduledValue: workPackage.scheduledValue || 0,
      workCompleted,
      materialsStored: 0,
      totalCompleted,
      retainage,
      currentBilling,
      previouslyBilled: 0,
      balance: (workPackage.scheduledValue || 0) - totalCompleted,
      workPackageId: workPackage.id,
      costCodeId: workPackage.costCodeId,
      autoGenerated: true,
      createdAt: new Date().toISOString()
    }

    sovItems.push(newLineItem)
    await spark.kv.set(sovItemsKey, sovItems)

    const updatedWorkPackages = await spark.kv.get<ExtendedWorkPackage[]>(`work-packages-${projectId}`) || []
    const wpIndex = updatedWorkPackages.findIndex(wp => wp.id === workPackage.id)
    if (wpIndex !== -1) {
      updatedWorkPackages[wpIndex] = {
        ...updatedWorkPackages[wpIndex],
        billedInSOVVersion: activeVersion.id
      }
      await spark.kv.set(`work-packages-${projectId}`, updatedWorkPackages)
    }

    return newLineItem
  } catch (error) {
    console.error('Error creating SOV line item from work package:', error)
    return undefined
  }
}

export async function updateFieldProgress(
  projectId: string,
  update: FieldProgressUpdate
): Promise<{ success: boolean; message: string; autoApprovedForBilling?: boolean }> {
  try {
    const workPackagesKey = `work-packages-${projectId}`
    const workPackagesData = await spark.kv.get<ExtendedWorkPackage[]>(workPackagesKey) || []
    
    const workPackageIndex = workPackagesData.findIndex(wp => wp.id === update.workPackageId)
    
    if (workPackageIndex === -1) {
      return {
        success: false,
        message: 'Work package not found'
      }
    }

    const updatedWorkPackage: ExtendedWorkPackage = {
      ...workPackagesData[workPackageIndex],
      status: update.status,
      percentComplete: update.percentComplete,
      updatedAt: update.updatedAt
    }

    workPackagesData[workPackageIndex] = updatedWorkPackage
    await spark.kv.set(workPackagesKey, workPackagesData)

    let autoApprovedForBilling = false
    if ((update.status === 'erected' || update.status === 'completed') && !updatedWorkPackage.approvedForBilling) {
      autoApprovedForBilling = true
    }

    return {
      success: true,
      message: 'Field progress updated successfully',
      autoApprovedForBilling
    }
  } catch (error) {
    console.error('Error updating field progress:', error)
    return {
      success: false,
      message: `Failed to update field progress: ${error}`
    }
  }
}

export async function syncAllErectedPackages(projectId: string): Promise<{
  success: boolean
  synced: number
  message: string
}> {
  try {
    const workPackagesKey = `work-packages-${projectId}`
    const workPackages = await spark.kv.get<ExtendedWorkPackage[]>(workPackagesKey) || []
    
    const erectedPackages = workPackages.filter(wp => 
      (wp.status === 'erected' || wp.status === 'completed') && 
      !wp.approvedForBilling
    )

    let syncedCount = 0
    for (const workPackage of erectedPackages) {
      const result = await approveWorkPackageForBilling(projectId, workPackage.id, 'System Auto-Sync')
      if (result.success) {
        syncedCount++
      }
    }

    return {
      success: true,
      synced: syncedCount,
      message: `Synced ${syncedCount} work package(s) to billing`
    }
  } catch (error) {
    console.error('Error syncing erected packages:', error)
    return {
      success: false,
      synced: 0,
      message: `Failed to sync packages: ${error}`
    }
  }
}

export function calculateBillingProgress(workPackages: ExtendedWorkPackage[]): {
  totalValue: number
  billedValue: number
  unbilledValue: number
  percentBilled: number
  pendingApproval: number
} {
  const totalValue = workPackages.reduce((sum, wp) => sum + (wp.scheduledValue || 0), 0)
  const billedValue = workPackages
    .filter(wp => wp.approvedForBilling)
    .reduce((sum, wp) => sum + ((wp.scheduledValue || 0) * wp.percentComplete / 100), 0)
  const unbilledValue = totalValue - billedValue
  const percentBilled = totalValue > 0 ? (billedValue / totalValue) * 100 : 0
  const pendingApproval = workPackages.filter(wp => 
    (wp.status === 'erected' || wp.status === 'completed') && !wp.approvedForBilling
  ).length

  return {
    totalValue,
    billedValue,
    unbilledValue,
    percentBilled,
    pendingApproval
  }
}

export interface FieldProgressUpdate {
  workPackageId: string
  status: WorkPackage['status']
  percentComplete: number
  updatedBy: string
  updatedAt: string
  notes?: string
}

export interface SOVLineItem {
  id: string
  versionId: string
  lineNumber: number
  description: string
  scheduledValue: number
  workCompleted: number
  materialsStored: number
  totalCompleted: number
  retainage: number
  currentBilling: number
  previouslyBilled: number
  balance: number
  workPackageId?: string
  costCodeId?: string
  autoGenerated: boolean
  createdAt: string
}

export interface BillingApprovalResult {
  success: boolean
  workPackage: WorkPackage
  sovLineItem?: SOVLineItem
  message: string
}

export async function approveWorkPackageForBilling(
  projectId: string,
  workPackageId: string,
  approvedBy: string
): Promise<BillingApprovalResult> {
  try {
    const workPackagesKey = `work-packages-${projectId}`
    const workPackagesData = await spark.kv.get<WorkPackage[]>(workPackagesKey) || []
    
    const workPackage = workPackagesData.find(wp => wp.id === workPackageId)
    
    if (!workPackage) {
      return {
        success: false,
        workPackage: null as any,
        message: 'Work package not found'
      }
    }

    if (workPackage.status !== 'erected' && workPackage.status !== 'completed') {
      return {
        success: false,
        workPackage,
        message: 'Work package must be erected or completed to approve for billing'
      }
    }

    if (workPackage.approvedForBilling) {
      return {
        success: false,
        workPackage,
        message: 'Work package already approved for billing'
      }
    }

    const updatedWorkPackage: WorkPackage = {
      ...workPackage,
      approvedForBilling: true,
      updatedAt: new Date().toISOString()
    }

    const updatedWorkPackages = workPackagesData.map(wp => 
      wp.id === workPackageId ? updatedWorkPackage : wp
    )
    await spark.kv.set(workPackagesKey, updatedWorkPackages)

    const sovLineItem = await createSOVLineItemFromWorkPackage(projectId, updatedWorkPackage)

    return {
      success: true,
      workPackage: updatedWorkPackage,
      sovLineItem,
      message: 'Work package approved for billing and added to SOV'
    }
  } catch (error) {
    console.error('Error approving work package for billing:', error)
    return {
      success: false,
      workPackage: null as any,
      message: `Failed to approve work package: ${error}`
    }
  }
}

async function createSOVLineItemFromWorkPackage(
  projectId: string,
  workPackage: WorkPackage
): Promise<SOVLineItem | undefined> {
  try {
    const sovVersionsKey = `sov-versions-${projectId}`
    const sovItemsKey = `sov-items-${projectId}`
    
    const sovVersions = await spark.kv.get<any[]>(sovVersionsKey) || []
    const sovItems = await spark.kv.get<SOVLineItem[]>(sovItemsKey) || []
    
    let activeVersion = sovVersions.find(v => v.status === 'draft')
    
    if (!activeVersion) {
      activeVersion = {
        id: uuidv4(),
        projectId,
        versionNumber: sovVersions.length + 1,
        periodStart: new Date().toISOString().split('T')[0],
        periodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        status: 'draft',
        retainagePercent: 10,
        createdAt: new Date().toISOString(),
        notes: 'Auto-generated from field progress'
      }
      sovVersions.push(activeVersion)
      await spark.kv.set(sovVersionsKey, sovVersions)
    }

    const existingLineItem = sovItems.find(item => 
      item.versionId === activeVersion.id && item.workPackageId === workPackage.id
    )

    if (existingLineItem) {
      return existingLineItem
    }

    const lineNumber = sovItems.filter(item => item.versionId === activeVersion.id).length + 1
    
    const workCompleted = workPackage.scheduledValue * (workPackage.percentComplete / 100)
    const totalCompleted = workCompleted
    const retainage = totalCompleted * (activeVersion.retainagePercent / 100)
    const currentBilling = totalCompleted - retainage

    const newLineItem: SOVLineItem = {
      id: uuidv4(),
      versionId: activeVersion.id,
      lineNumber,
      description: workPackage.name,
      scheduledValue: workPackage.scheduledValue,
      workCompleted,
      materialsStored: 0,
      totalCompleted,
      retainage,
      currentBilling,
      previouslyBilled: 0,
      balance: workPackage.scheduledValue - totalCompleted,
      workPackageId: workPackage.id,
      costCodeId: workPackage.costCodeId,
      autoGenerated: true,
      createdAt: new Date().toISOString()
    }

    sovItems.push(newLineItem)
    await spark.kv.set(sovItemsKey, sovItems)

    const updatedWorkPackages = await spark.kv.get<WorkPackage[]>(`work-packages-${projectId}`) || []
    const wpIndex = updatedWorkPackages.findIndex(wp => wp.id === workPackage.id)
    if (wpIndex !== -1) {
      updatedWorkPackages[wpIndex] = {
        ...updatedWorkPackages[wpIndex],
        billedInSOVVersion: activeVersion.id
      }
      await spark.kv.set(`work-packages-${projectId}`, updatedWorkPackages)
    }

    return newLineItem
  } catch (error) {
    console.error('Error creating SOV line item from work package:', error)
    return undefined
  }
}

export async function updateFieldProgress(
  projectId: string,
  update: FieldProgressUpdate
): Promise<{ success: boolean; message: string; autoApprovedForBilling?: boolean }> {
  try {
    const workPackagesKey = `work-packages-${projectId}`
    const workPackagesData = await spark.kv.get<WorkPackage[]>(workPackagesKey) || []
    
    const workPackageIndex = workPackagesData.findIndex(wp => wp.id === update.workPackageId)
    
    if (workPackageIndex === -1) {
      return {
        success: false,
        message: 'Work package not found'
      }
    }

    const updatedWorkPackage: WorkPackage = {
      ...workPackagesData[workPackageIndex],
      status: update.status,
      percentComplete: update.percentComplete,
      updatedAt: update.updatedAt
    }

    workPackagesData[workPackageIndex] = updatedWorkPackage
    await spark.kv.set(workPackagesKey, workPackagesData)

    let autoApprovedForBilling = false
    if ((update.status === 'erected' || update.status === 'completed') && !updatedWorkPackage.approvedForBilling) {
      autoApprovedForBilling = true
    }

    return {
      success: true,
      message: 'Field progress updated successfully',
      autoApprovedForBilling
    }
  } catch (error) {
    console.error('Error updating field progress:', error)
    return {
      success: false,
      message: `Failed to update field progress: ${error}`
    }
  }
}

export async function syncAllErectedPackages(projectId: string): Promise<{
  success: boolean
  synced: number
  message: string
}> {
  try {
    const workPackagesKey = `work-packages-${projectId}`
    const workPackages = await spark.kv.get<WorkPackage[]>(workPackagesKey) || []
    
    const erectedPackages = workPackages.filter(wp => 
      (wp.status === 'erected' || wp.status === 'completed') && 
      !wp.approvedForBilling
    )

    let syncedCount = 0
    for (const workPackage of erectedPackages) {
      const result = await approveWorkPackageForBilling(projectId, workPackage.id, 'System Auto-Sync')
      if (result.success) {
        syncedCount++
      }
    }

    return {
      success: true,
      synced: syncedCount,
      message: `Synced ${syncedCount} work package(s) to billing`
    }
  } catch (error) {
    console.error('Error syncing erected packages:', error)
    return {
      success: false,
      synced: 0,
      message: `Failed to sync packages: ${error}`
    }
  }
}

export function calculateBillingProgress(workPackages: WorkPackage[]): {
  totalValue: number
  billedValue: number
  unbilledValue: number
  percentBilled: number
  pendingApproval: number
} {
  const totalValue = workPackages.reduce((sum, wp) => sum + wp.scheduledValue, 0)
  const billedValue = workPackages
    .filter(wp => wp.approvedForBilling)
    .reduce((sum, wp) => sum + (wp.scheduledValue * wp.percentComplete / 100), 0)
  const unbilledValue = totalValue - billedValue
  const percentBilled = totalValue > 0 ? (billedValue / totalValue) * 100 : 0
  const pendingApproval = workPackages.filter(wp => 
    (wp.status === 'erected' || wp.status === 'completed') && !wp.approvedForBilling
  ).length

  return {
    totalValue,
    billedValue,
    unbilledValue,
    percentBilled,
    pendingApproval
  }
}
